---
# Encrypted variables for production
vault_smtp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38636264613831336564376332393765386134366432346261366531346564666464366430646530
          6131663862383436383338636133393134633630616266620a313933346266366239343566646239
          34336534316636636364326231343837326332363664626331646238613539383131343635343635
          3439343638336264340a626339323338646537363637623862653062633437626637653963303536
          3032

vault_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323334353637383930313233343536373839303132333435363738393031323334353637383930
          31323334353637383930313233343536373839303132333435363738393031323334353637383930
          31320a

# Encrypted user passwords
vault_mail_users:
  - username: admin
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323334353637383930313233343536373839303132333435363738393031323334353637383930
          31323334353637383930313233343536373839303132333435363738393031323334353637383930
          31320a
