---
- name: restart postfix
  systemd:
    name: postfix
    state: restarted

- name: reload postfix
  systemd:
    name: postfix
    state: reloaded

- name: restart dovecot
  systemd:
    name: dovecot
    state: restarted

- name: reload dovecot
  systemd:
    name: dovecot
    state: reloaded
